name: Deploy
# on:
#   push:
#     branches: [ main ]
on: [push]

jobs:
  deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GH_ACTIONS_PUSH_MAIN_TOKEN }}

      - name: Install packages
        run: npm install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        run: npm run deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # - name: Deploy app on gh pages
      #   run: npm run deploy
