name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GH_ACTIONS_PUSH_MAIN_TOKEN }}

      - name: Install packages
        run: npm install

      - name: Add dummy git credentials
        run: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"

      - name: Deploy app on gh pages
        run: npm run deploy
