name: General

on: [push]

jobs:
  general-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Format with Prettier - fix if possible
        run: npm run prettier -- --write

      - name: Lint with eslint - fix if possible
        run: npm run lint -- --fix